language: java
jdk: openjdk8
sudo: required
services:
  - docker
install:
  - mvn clean
script:
  - mvn install -B -V
after_success:
  - bash <(curl -s https://codecov.io/bash) -t db72c61d-aa61-4b80-9ffd-1a135d29a85f
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - ./mvnw dockerfile:push@push-latest dockerfile:push@push-version -DskipTests
deploy:
  provider: bintray
  file: descriptor.json
  user: $BINTRAY_USER
  key: $BINTRAY_API_KEY
