language: java
sudo: required
services:
  - docker
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./gradlew pushDockerImages
deploy:
  provider: script
  script:
    - ./gradlew bintrayUpload
  skip_cleanup: true
  on:
    tags: true