language: java
sudo: required
services:
  - docker
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - ./gradlew pushImageVersion
deploy:
  provider: script
  script:
    - ./gradlew pushImageLatest bintrayUpload
  skip_cleanup: true
  on:
    tags: true